PUT https://my-app-logic.onrender.com/user/3/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njc1NjY2MzYsInJvbGUiOiJzdHVkZW50IiwidXNlcl9pZCI6M30.pl-pHWhLiJpXwFRJe4ZTkhtK_td_l2ILPuUseqlZ2j0

{
  "role": "teacher"
}