#include "server.h"
#include "auth.h"
#include "config.h"
#include <winsock2.h>
#include <ws2tcpip.h>
#include <iostream>
#include <sstream>
#include <regex>

using namespace std;

#pragma comment(lib, "ws2_32.lib")

void sendResponse(int client, const string& content, bool json = false) {
    string response = "HTTP/1.1 200 OK\r\n";
    response += "Content-Type: " + string(json ? "application/json" : "text/html; charset=utf-8") + "\r\n";
    response += "Access-Control-Allow-Origin: *\r\n";
    response += "Access-Control-Allow-Methods: GET, POST, OPTIONS\r\n";
    response += "Access-Control-Allow-Headers: Content-Type\r\n";
    response += "Connection: close\r\n";
    response += "\r\n" + content;
    
    send(client, response.c_str(), response.length(), 0);
}

void sendError(int client, const string& error, int code = 400) {
    string response = "HTTP/1.1 " + to_string(code) + " " + 
                     (code == 401 ? "Unauthorized" : "Bad Request") + "\r\n";
    response += "Content-Type: application/json\r\n";
    response += "Connection: close\r\n\r\n";
    response += "{\"error\":\"" + error + "\"}";
    
    send(client, response.c_str(), response.length(), 0);
}

string readRequest(int client) {
    char buffer[8192] = {0};  // Увеличил буфер
    int bytes = recv(client, buffer, sizeof(buffer), 0);
    if (bytes <= 0) return "";
    return string(buffer, bytes);
}

map<string, string> parseFormData(const string& body) {
    map<string, string> params;
    istringstream iss(body);
    string pair;
    
    while (getline(iss, pair, '&')) {
        size_t eq = pair.find('=');
        if (eq != string::npos) {
            string key = pair.substr(0, eq);
            string value = pair.substr(eq + 1);
            // Простой URL decode
            string decoded;
            for (size_t i = 0; i < value.length(); ++i) {
                if (value[i] == '%' && i + 2 < value.length()) {
                    int hex;
                    sscanf(value.substr(i + 1, 2).c_str(), "%x", &hex);
                    decoded += (char)hex;
                    i += 2;
                } else if (value[i] == '+') {
                    decoded += ' ';
                } else {
                    decoded += value[i];
                }
            }
            params[key] = decoded;
        }
    }
    return params;
}

// ========== ГЛАВНЫЙ ОБРАБОТЧИК ==========

void handleClient(int client) {
    string request = readRequest(client);
    if (request.empty()) return;
    
    // Получаем метод и путь
    istringstream ss(request);
    string method, path, version;
    ss >> method >> path >> version;
    
    cout << "[" << method << "] " << path << endl;
    
    // ========== CORS PREFLIGHT ==========
    if (method == "OPTIONS") {
        sendResponse(client, "");
        return;
    }
    
    // ========== ИНФО О API ==========
    if (path == "/" || path == "/api" || path == "/auth") {
        string apiInfo = R"({
    "service": "Authentication Module",
    "version": "1.0",
    "description": "This is a pure API module for user authentication",
    "endpoints": {
        "register": {"method": "POST", "path": "/auth/register", "desc": "Register new user"},
        "login": {"method": "POST", "path": "/auth/login", "desc": "Login with credentials"},
        "oauth_start": {"method": "GET", "path": "/auth/oauth?login_token=TOKEN", "desc": "Start GitHub OAuth"},
        "oauth_callback": {"method": "GET", "path": "/auth/callback?code=CODE&state=STATE", "desc": "GitHub OAuth callback"},
        "verify": {"method": "GET", "path": "/auth/verify?token=TOKEN", "desc": "Verify JWT token"},
        "refresh": {"method": "POST", "path": "/auth/refresh", "desc": "Refresh access token"},
        "telegram": {"method": "POST", "path": "/auth/telegram", "desc": "Telegram bot authentication"}
    },
    "note": "All responses are in JSON format. No HTML is generated by this module."
})";
        sendResponse(client, apiInfo, true);
        return;
    }
    
    // ========== РЕГИСТРАЦИЯ ==========
    if (path == "/auth/register" && method == "POST") {
        size_t body_start = request.find("\r\n\r\n");
        if (body_start == string::npos) {
            sendError(client, "Missing request body");
            return;
        }
        
        string body = request.substr(body_start + 4);
        auto params = parseFormData(body);
        
        string login = params["login"];
        string password = params["password"];
        string fullname = params["fullname"];
        string email = params["email"];
        
        if (login.empty() || password.empty() || fullname.empty() || email.empty()) {
            sendError(client, "All fields are required");
            return;
        }
        
        string result = Auth::registerUser(login, password, fullname, email);
        sendResponse(client, result, true);
        return;
    }
    
    // ========== АВТОРИЗАЦИЯ ==========
    if (path == "/auth/login" && method == "POST") {
        size_t body_start = request.find("\r\n\r\n");
        if (body_start == string::npos) {
            sendError(client, "Missing request body");
            return;
        }
        
        string body = request.substr(body_start + 4);
        auto params = parseFormData(body);
        
        string login = params["login"];
        string password = params["password"];
        
        if (login.empty() || password.empty()) {
            sendError(client, "Login and password required");
            return;
        }
        
        string result = Auth::loginUser(login, password);
        sendResponse(client, result, true);
        return;
    }
    
    // ========== СТАРТ OAUTH ==========
    if (path.find("/auth/oauth?") == 0) {
        size_t token_pos = path.find("login_token=");
        if (token_pos != string::npos) {
            string token = path.substr(token_pos + 12);
            // Убираем возможные параметры после токена
            size_t amp_pos = token.find('&');
            if (amp_pos != string::npos) {
                token = token.substr(0, amp_pos);
            }
            
            string result = Auth::startOAuth(token);
            sendResponse(client, result, true);
        } else {
            sendError(client, "Missing login_token parameter");
        }
        return;
    }
    
    // ========== CALLBACK GITHUB ==========
    if (path.find("/auth/callback?") == 0) {
        regex param_regex("code=([^&]+)&state=([^&\\s]+)");
        smatch matches;
        
        if (regex_search(path, matches, param_regex) && matches.size() == 3) {
            string code = matches[1];
            string state = matches[2];
            
            string result = Auth::handleGitHubCallback(code, state);
            sendResponse(client, result, true);
        } else {
            // Попробуем альтернативный парсинг
            size_t code_pos = path.find("code=");
            size_t state_pos = path.find("&state=");
            
            if (code_pos != string::npos) {
                string code, state;
                
                if (state_pos != string::npos) {
                    code = path.substr(code_pos + 5, state_pos - (code_pos + 5));
                    state = path.substr(state_pos + 7);
                    size_t end_pos = state.find('&');
                    if (end_pos != string::npos) {
                        state = state.substr(0, end_pos);
                    }
                } else {
                    code = path.substr(code_pos + 5);
                    state = "";
                }
                
                string result = Auth::handleGitHubCallback(code, state);
                sendResponse(client, result, true);
            } else {
                sendError(client, "Invalid callback parameters");
            }
        }
        return;
    }
    
    // ========== ТЕЛЕГРАМ AUTH ==========
    if (path == "/auth/telegram" && method == "POST") {
        size_t body_start = request.find("\r\n\r\n");
        if (body_start == string::npos) {
            sendError(client, "Missing request body");
            return;
        }
        
        string body = request.substr(body_start + 4);
        auto params = parseFormData(body);
        
        string telegram_id = params["telegram_id"];
        string name = params["name"];
        
        if (telegram_id.empty() || name.empty()) {
            sendError(client, "telegram_id and name required");
            return;
        }
        
        string result = Auth::telegramAuth(telegram_id, name);
        sendResponse(client, result, true);
        return;
    }
    
    // ========== VERIFY TOKEN ==========
    if (path.find("/auth/verify?") == 0) {
        size_t token_pos = path.find("token=");
        if (token_pos != string::npos) {
            string token = path.substr(token_pos + 6);
            // Убираем возможные параметры после токена
            size_t amp_pos = token.find('&');
            if (amp_pos != string::npos) {
                token = token.substr(0, amp_pos);
            }
            
            string result = Auth::verifyToken(token);
            sendResponse(client, result, true);
        } else {
            sendError(client, "Missing token parameter");
        }
        return;
    }
    
    // ========== REFRESH TOKEN ==========
    if (path == "/auth/refresh" && method == "POST") {
        size_t body_start = request.find("\r\n\r\n");
        if (body_start == string::npos) {
            sendError(client, "Missing request body");
            return;
        }
        
        string body = request.substr(body_start + 4);
        auto params = parseFormData(body);
        
        string refresh_token = params["refresh_token"];
        
        if (refresh_token.empty()) {
            sendError(client, "refresh_token required");
            return;
        }
        
        string result = Auth::refreshToken(refresh_token);
        sendResponse(client, result, true);
        return;
    }
    
    // ========== ОБРАБОТКА СТАРЫХ ЭНДПОИНТОВ (для обратной совместимости) ==========
    if (path == "/api/telegram" && method == "POST") {
        // Перенаправляем на новый эндпоинт
        size_t body_start = request.find("\r\n\r\n");
        if (body_start != string::npos) {
            string body = request.substr(body_start + 4);
            auto params = parseFormData(body);
            
            string telegram_id = params["telegram_id"];
            string name = params["name"];
            
            if (!telegram_id.empty() && !name.empty()) {
                string result = Auth::telegramAuth(telegram_id, name);
                sendResponse(client, result, true);
            } else {
                sendError(client, "Missing parameters");
            }
        }
        return;
    }
    
    if (path.find("/api/verify?") == 0) {
        // Перенаправляем на новый эндпоинт
        size_t token_pos = path.find("token=");
        if (token_pos != string::npos) {
            string token = path.substr(token_pos + 6);
            size_t amp_pos = token.find('&');
            if (amp_pos != string::npos) {
                token = token.substr(0, amp_pos);
            }
            
            string result = Auth::verifyToken(token);
            sendResponse(client, result, true);
        } else {
            sendError(client, "Missing token parameter");
        }
        return;
    }
    
    // ========== ВСЕ ОСТАЛЬНЫЕ ЗАПРОСЫ ==========
    sendError(client, "Endpoint not found", 404);
}

void HttpServer::start(int port) {
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        cerr << "Ошибка WSAStartup" << endl;
        return;
    }
    
    SOCKET server = socket(AF_INET, SOCK_STREAM, 0);
    if (server == INVALID_SOCKET) {
        cerr << "Ошибка создания сокета" << endl;
        WSACleanup();
        return;
    }
    
    // Устанавливаем опцию для повторного использования порта
    int opt = 1;
    setsockopt(server, SOL_SOCKET, SO_REUSEADDR, (char*)&opt, sizeof(opt));
    
    sockaddr_in addr;
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(port);
    
    if (bind(server, (sockaddr*)&addr, sizeof(addr)) == SOCKET_ERROR) {
        cerr << "Ошибка bind: " << WSAGetLastError() << endl;
        closesocket(server);
        WSACleanup();
        return;
    }
    
    if (listen(server, 10) == SOCKET_ERROR) {
        cerr << "Ошибка listen" << endl;
        closesocket(server);
        WSACleanup();
        return;
    }
    
    cout << "\n==========================================" << endl;
    cout << "🚀 Модуль авторизации успешно запущен!" << endl;
    cout << "📍 Порт: " << port << endl;
    cout << "🌐 URL: http://localhost:" << port << endl;
    cout << "\n📡 Доступные эндпоинты:" << endl;
    cout << "   POST /auth/register    - Регистрация" << endl;
    cout << "   POST /auth/login       - Авторизация" << endl;
    cout << "   GET  /auth/oauth       - Старт OAuth" << endl;
    cout << "   GET  /auth/callback    - GitHub callback" << endl;
    cout << "   POST /auth/telegram    - Telegram auth" << endl;
    cout << "   GET  /auth/verify      - Проверка токена" << endl;
    cout << "   POST /auth/refresh     - Обновление токена" << endl;
    cout << "\n✅ Готов к работе с другими модулями!" << endl;
    cout << "==========================================\n" << endl;
    
    while (true) {
        SOCKET client = accept(server, nullptr, nullptr);
        if (client != INVALID_SOCKET) {
            handleClient(client);
            closesocket(client);
        }
    }
    
    closesocket(server);
    WSACleanup();
}